### ISSUE TITLE
Option for Line to fade out/not show if mobile is at 100% health

### ISSUE THREAD

**Issue by BlackTeaOutlands** [ClassicUO/ClassicUO#604]
I would like the option for the Line to fade/not show if the mobile is at 100% health. Reason is mainly, it doesn't look very good in town for example to see all those lines everywhere which don't serve any purpose.

![image](https://user-images.githubusercontent.com/39037141/61190327-dd54b000-a69a-11e9-9edb-02b0dddc80eb.png)

**Comment by binff04** [comment]
I remember that in OrionUO there was the exact setting for that, something like "Show health lines only if less than full health".

**Comment by BlackTeaOutlands** [comment]
In the recent dev build I also now get the overhead text constantly showing if I enable this option. I don't think this is desirable. The overhead Percentage only should show if the HP changes.

You would possibly want the Line to always show. But I don't think anyone ever wants the overhead text to Always show. So I suggest either have the "Always" option only be in regards to the Line, or make the option more diverse so you can pick how it applies to Line or Percentage seperately.

![image](https://user-images.githubusercontent.com/39037141/61294453-1f364100-a7d6-11e9-8840-f269283bba59.png)

**Comment by zolter** [comment]
I'll check, thanks

**Comment by BlackTeaOutlands** [comment]
Can I open this issue again, or do you mind?

I also noticed that overhead text is offset to the right. The circled text is supposed to be where the arrow points.

![image](https://user-images.githubusercontent.com/39037141/61416962-db3a5d80-a8f5-11e9-96a4-f1171f60ae16.png)

**Comment by andreakarasho** [comment]
done a fix.
Lemme know

**Comment by BlackTeaOutlands** [comment]
Correct position now, but overhead text still always displays. Should only display change in HP, even if you have the "Always show" option enabled.

**Comment by andreakarasho** [comment]
use Smart option no alwasy

**Comment by BlackTeaOutlands** [comment]
**Nevermind**

Ok I found the smart option. One thing to add to that: I don't think Percentage should always show when it is below 100% (with the Smart Option). It should be like a text message that just fades in & out - pretty sure that's not the case?

**Comment by BlackTeaOutlands** [comment]
Just want to reiterate that even though there is a smart option - this issue is not resolved yet.

The point of the overhead text is still to show changes in HP (and that was how it worked before my request to add an option for Line to fade out was implemented).

With Smart Option, the overhead text will still always show when it is below 100%. It also loses some functionality, because before you could cast Weaken on someone and see the overhead message trigger (even if they are at 100%) due to a change in HP. This no longer works in CUO.

So - the current overhead HP text is broken & does not work as it should.
