### ISSUE TITLE
Multi Boat Hue

### ISSUE THREAD

**Issue by Djeryv** [ClassicUO/ClassicUO#738]
There is a couple of odd issues with boat. First, the boats in my server are partial hue but you can see from the screenshot that the sails are not white like on the original client. The tillerman, however, is being partial hue but you interract with that piece (not part of the multi). Also, for some reason, I can select the mast when I hover over it.

![image](https://user-images.githubusercontent.com/49735284/65822790-dc4e0c00-e20f-11e9-8614-44eb70270fc3.png)

**Comment by andreakarasho** [comment]
should be fixed

**Comment by Djeryv** [comment]
The mast selection is fixed, but the partial hue still isn't working. Here is a picture of the same boat on the regular client:

![image](https://user-images.githubusercontent.com/49735284/65830563-32559a80-e276-11e9-95d2-6610991f848d.png)

**Comment by Djeryv** [comment]
I just compiled the dev this morning as an FYI.

**Comment by andreakarasho** [comment]
Ok i've done a fix.
Basically multi objects now are affected by itemdata.partialhue

**Comment by Djeryv** [comment]
Getting closer...but that mast is still not behaving...

![image](https://user-images.githubusercontent.com/49735284/65835266-c4c36180-e2a9-11e9-8443-b8e5e3fb9da6.png)

**Comment by andreakarasho** [comment]
recheck please :D

**Comment by Djeryv** [comment]
Still the same...no change. I know you got rid of the "highlight the mast" issue but I can still hover my mouse over the mast and get a window showing "mast" and the weight...which does not happen on the regular client. The entire multi (except tillerman and doors, a just a multi.

![image](https://user-images.githubusercontent.com/49735284/65836047-859a0e00-e2b3-11e9-8594-d70d14c1b1d0.png)

**Comment by andreakarasho** [comment]
done another set of fixes.
About selectable Mast it is a wanted behaviour or a minor issue if you prefer :)

![image](https://user-images.githubusercontent.com/20810422/65837408-5efdc680-e2f7-11e9-8a9f-2c0ac8fb7978.png)

![image](https://user-images.githubusercontent.com/20810422/65837414-6c1ab580-e2f7-11e9-9bb4-260fdca94142.png)

**Comment by andreakarasho** [comment]
Fixed
